# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pr:
- main

pool:
  vmImage: ubuntu-latest

#steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

jobs:
  - job: PushEcho
    displayName: Trigger None Test Branch echo when push happens
    steps:
      - task: CmdLine@2
        inputs:
          script: echo TRIGGER NONE TEST BRANCH Complete.
