trigger:
- main 

resources:
- repo: self 

parameters:
  - name: ValueA
    displayName: Value A
    default: A
    type: string
  - name: ValueB
    displayName: Value B
    default: B
    type: string
  - name: Myname
    displayName: My Name
    default: Madesh
    type: string

variables:
  env: qa
  imageName: test-java-app
  tag: $(Build.BuildId)
  imagePullSecret: my-app-secret
  vmImageName: ubuntu-latest
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

pool:
  vmImage: $(vmImageName)

stages:


- stage: Build 
  displayName: Build stage 
  jobs:
  - job: Build 
    displayName: Build 
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-X.xml'
        goals: 'package'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          java -jar $(Build.ArtifactStagingDirectory)/**/*war
        

    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '874685fc-027a-4439-aaa9-171e5ead0f59/7e134717-36d8-45f9-a518-d69ba6f2673a'
        vstsFeedPackagePublish: 'javapp'
        versionOption: 'custom'
        versionPublish: '1.1.0'
    
