variables:
- group: "test-vars"
- name: imageNa
  value: $[variables.imageName]
parameters:
- name: image
  displayName: Pool Image
  values:
    - windows-latest
    - ubuntu-latest
    - macOS-latest
- name: test
  displayName: Run Tests?
  type: boolean
  default: false

trigger: none
 
jobs: 
- job: build
  displayName: Build and Test
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(imageNa)
  #- ${{ if eq(parameters.test, true)}}:
  - script: echo "Running all the tests"
  - script: cd $(Build.ArtifactStagingDirectory)
  - script: ls -lrt