trigger:
- main 

resources:
- repo: self 

variables:
  env: qa
  imageName: test-java-app
  tag: $(Build.BuildId)
  imagePullSecret: my-app-secret
  vmImageName: ubuntu-latest
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

pool:
  vmImage: $(imageName)

stages:

- stage: PR_Build
  displayName: Pull Request Build 
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/pull'))
  jobs:
    - job: Build
      displayName: PR-Build stage
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-X.xml'
          goals: 'package'
      
- stage: Build 
  displayName: Build stage 
  jobs:
  - job: Build 
    displayName: Build 
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-X.xml'
        goals: 'package'


        

    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '874685fc-027a-4439-aaa9-171e5ead0f59/7e134717-36d8-45f9-a518-d69ba6f2673a'
        vstsFeedPackagePublish: 'javapp'
        versionOption: 'custom'
        versionPublish: '1.0.0'
    
