# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)
variables:
  - group: external-variables
  - name: buildId
    value: '$(Build.BuildId)'
  - name: System.Debug
    value: true

stages :

- stage: Status
  displayName: Get Builds by Commit
  jobs:
    - job:   
      displayName: Get Builds by Commit
      variables:
        AUTH : "Authorization: Bearer $(System.AccessToken)"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: curl -X GET -H '$(AUTH)' "$( echo "https://dev.azure.com/thierrychantier/$(System.TeamProject)/_apis/build/builds" | sed 's/ /%20/g' )" >> output.txt
        - script: cat output.txt
        - script: cat output.txt | jq -c '. .value[] | select(.sourceVersion | contains("$(Build.SourceVersion)")) | .id'

- stage: Build
  displayName: Build stage

  jobs:  
    - job: Test
      displayName: Job Test
      timeoutInMinutes: 0 # 0 veut dire max value, par défaut c'est 60 minutes pour windows agent sur un git privé
      pool:
        name: 'BuildAgentPool'
      steps:
      - task: Maven@3
        displayName: UnitTest
        condition: and(not(contains(variables['Build.SourceVersionMessage'], '@noci')),not(contains(variables['Build.SourceVersionMessage'], '@notests')))
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: '/usr/lib/jvm/java-8-openjdk-amd64'
          jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
          jdkVersionOption: '1.8'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'test -P UnitTest'
      - task: Maven@3
        displayName: DBTest
        condition: or(eq(variables['runDbTest'], 'true'), and(not(contains(variables['Build.SourceVersionMessage'], '@noci')), contains(variables['Build.SourceVersionMessage'], '@dbtests')))
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: '/usr/lib/jvm/java-8-openjdk-amd64'
          jdkDirectory: '/usr/lib/jvm/java-8-openjdk-amd64'
          jdkVersionOption: '1.8'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'test -P DBTest'
      - task: PublishTestResults@2
        displayName: Merge Test Results
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml' 
          mergeTestResults: true
      - task: AzureFileCopy@4
        inputs:
          sourcePath: '**/surefire-reports/TEST-*.xml'
          azureSubscription: 'thierry-sandox'
          destination: AzureBlob
          storage: 
          containerName: # Required when destination == AzureBlob
          #blobPrefix: # Optional
          #resourceGroup: # Required when destination == AzureVMs
          #resourceFilteringMethod: 'machineNames' # Optional. Options: machineNames, tags
          #machineNames: # Optional
          #vmsAdminUserName: # Required when destination == AzureVMs
          #vmsAdminPassword: # Required when destination == AzureVMs
          #targetPath: # Required when destination == AzureVMs
          #additionalArgumentsForBlobCopy: # Optional
          #additionalArgumentsForVMCopy: # Optional
          #enableCopyPrerequisites: false # Optional
          #copyFilesInParallel: true # Optional
          #cleanTargetBeforeCopy: false # Optional
          #skipCACheck: true # Optional
          #sasTokenTimeOutInMinutes: # Optional

- stage: Package
  displayName: Package stage
  
  jobs:  
    - job: Test
      displayName: Job Test
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Maven@3
        displayName: Package
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          goals: 'package -DskipTests=true'
      - task: CopyFiles@2
        inputs:
          contents: 'target/**.war'
          targetFolder: $(Build.ArtifactStagingDirectory)
      # - task: PublishBuildArtifacts@1 ## Deprecated
      #   inputs:
      #     pathToPublish: $(Build.ArtifactStagingDirectory)
      #     artifactName: MonWarBuild
      - task: PublishPipelineArtifact@1 ## Recommended
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: MonWarPipeline            

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Package
  condition: succeeded('Package')
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'no_approbation'
    strategy:
      runOnce:
        deploy:
          steps:
            
            - task: DownloadPipelineArtifact@2 ## Recommended
              inputs:
                artifact: MonWarPipeline
                buildId: 106
            - task: DownloadPipelineArtifact@2 ## Recommended
              inputs:
                artifact: MonWarPipeline
            # - task: DownloadBuildArtifacts@0 ## Deprecated
            #   inputs:
            #     artifactName: MonWarBuild