# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: 1  # build numbering format
variables:
  buildId: '$(Build.BuildId)'
stages :
- stage:
  displayName: Stage Test

  jobs:  
    - job:
      displayName: Job Test
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

    - job:
      displayName: Job Test 2
      pool:
        vmImage: 'ubuntu-16.04'
      steps:
      - bash: echo "Hello world $buildId"
