trigger:
  batch: true
  branches:
    include:
    - master
    - release*
    exclude:
    - releases/old1*

jobs:
  - job: Test
    strategy:
      maxParallel: 2
      matrix: 
        US_IE:
          Location: US
          Browser: IE
        US_Chrome:
          Location: US
          Browser: Chrome
        Europe_Chrome:
          Location: Europe
          Browser: Chrome