jobs:
  - job: InitialA
    steps:
    - script: echo hello from initial A
  - job: InitialB
    steps:
    - script: echo hello from initial B
  - job: Subsequent
    dependsOn:
    - InitialA
    - InitialB
    steps:
    - script: echo hello from subsequent