# Compilación y Pruebas Proyecto Java
name: Compilación Java

on:
  # se ejecuta el flujo con cada push y pull request B
  # o haciendo clic desde las opciones de Github Actions 
  [push, pull_request, workflow_dispatch]

jobs:
  build:

    # se ejecuta en Ubuntu Linux
    runs-on: ubuntu-latest

    # acciones a ejecutar
    steps:
    - name: Descarga el código fuente
      uses: actions/checkout@v2

    - name: Configura JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '11'

    - name: Compila el proyecto y ejecuta las pruebas
      run: mvn -B package --file pom.xml
